name: my-ci
on: [push] 
jobs: 
  build-deploy_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - uses: docker/build-push-action@v5
        with:
          tags: getting-started:latest